package com.myster.type.join;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.nio.ByteBuffer;
import java.nio.charset.CharacterCodingException;
import java.nio.charset.CodingErrorAction;
import java.nio.charset.StandardCharsets;
import java.util.HashMap;
import java.util.HexFormat;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import java.util.regex.Pattern;

import com.myster.cid.ServerCid;
import com.myster.type.MysterType;

/**
 * Immutable version 1 private-type invitation URI.
 *
 * <p>The canonical form is
 * {@code myster://join-type/v1?type=<hex>&bootstrap=<hex>&invitation=<hex>}, where every value is
 * exactly 16 bytes encoded as 32 lowercase hexadecimal characters. Parsing accepts query fields in
 * any order and one optional percent-encoded {@code code}, but generated and diagnostic forms never
 * include the code.
 */
public final class TypeJoinUri {
    public static final int INVITATION_ID_BYTES = 16;
    public static final int MAX_URI_CHARS = 4 * 1024;
    public static final int MAX_CODE_POINTS = 256;

    private static final Pattern LOWER_HEX_128 = Pattern.compile("[0-9a-f]{32}");
    private static final HexFormat HEX = HexFormat.of();

    private final MysterType type;
    private final ServerCid bootstrap;
    private final byte[] invitationId;
    private final Optional<String> code;

    private TypeJoinUri(MysterType type, ServerCid bootstrap, byte[] invitationId,
            Optional<String> code) {
        this.type = Objects.requireNonNull(type, "type");
        this.bootstrap = Objects.requireNonNull(bootstrap, "bootstrap");
        if (Objects.requireNonNull(invitationId, "invitationId").length != INVITATION_ID_BYTES) {
            throw new IllegalArgumentException("Invitation id must be 16 bytes");
        }
        this.invitationId = invitationId.clone();
        this.code = Objects.requireNonNull(code, "code");
    }

    /** Creates the canonical, password-free URI generated by this Myster version. */
    public static TypeJoinUri create(MysterType type, ServerCid bootstrap, byte[] invitationId) {
        return new TypeJoinUri(type, bootstrap, invitationId, Optional.empty());
    }

    /**
     * Parses and validates a complete invitation URI.
     *
     * @throws IOException if the URI is malformed, oversized, duplicated, or outside version 1
     */
    public static TypeJoinUri parse(String text) throws IOException {
        Objects.requireNonNull(text, "text");
        if (text.length() > MAX_URI_CHARS) {
            throw new IOException("Invitation URI is too long");
        }

        URI uri;
        try {
            uri = new URI(text);
        } catch (URISyntaxException exception) {
            throw new IOException("Invalid invitation URI", exception);
        }
        if (uri.getScheme() == null || !"myster".equalsIgnoreCase(uri.getScheme())
                || !"join-type".equals(uri.getRawAuthority())
                || !"/v1".equals(uri.getRawPath())
                || uri.getRawFragment() != null
                || uri.getRawUserInfo() != null
                || uri.getPort() != -1) {
            throw new IOException("Unsupported invitation URI");
        }

        Map<String, String> known = parseQuery(uri.getRawQuery());
        String typeHex = requiredHex(known, "type");
        String bootstrapHex = requiredHex(known, "bootstrap");
        String invitationHex = requiredHex(known, "invitation");
        Optional<String> code = Optional.ofNullable(known.get("code"));
        if (code.isPresent() && (code.get().isEmpty()
                || code.get().codePointCount(0, code.get().length()) > MAX_CODE_POINTS)) {
            throw new IOException("Invitation code must contain 1 to 256 characters");
        }

        try {
            return new TypeJoinUri(
                    MysterType.fromHexString(typeHex),
                    new ServerCid(HEX.parseHex(bootstrapHex)),
                    HEX.parseHex(invitationHex),
                    code);
        } catch (IllegalArgumentException exception) {
            throw new IOException("Invalid invitation identity", exception);
        }
    }

    private static Map<String, String> parseQuery(String rawQuery) throws IOException {
        if (rawQuery == null || rawQuery.isEmpty()) {
            throw new IOException("Invitation URI has no query");
        }
        Map<String, String> known = new HashMap<>();
        for (String field : rawQuery.split("&", -1)) {
            int equals = field.indexOf('=');
            if (equals <= 0) {
                throw new IOException("Malformed invitation query field");
            }
            String name = field.substring(0, equals);
            if (!name.equals("type") && !name.equals("bootstrap")
                    && !name.equals("invitation") && !name.equals("code")) {
                continue;
            }
            if (known.containsKey(name)) {
                throw new IOException("Duplicate invitation query field: " + name);
            }
            String rawValue = field.substring(equals + 1);
            known.put(name, name.equals("code") ? decodeUtf8(rawValue) : rawValue);
        }
        return known;
    }

    private static String requiredHex(Map<String, String> known, String name) throws IOException {
        String value = known.get(name);
        if (value == null || !LOWER_HEX_128.matcher(value).matches()) {
            throw new IOException("Invalid or missing " + name);
        }
        return value;
    }

    private static String decodeUtf8(String raw) throws IOException {
        ByteArrayOutputStream bytes = new ByteArrayOutputStream(raw.length());
        for (int index = 0; index < raw.length();) {
            char ch = raw.charAt(index);
            if (ch == '%') {
                if (index + 2 >= raw.length()) {
                    throw new IOException("Malformed percent encoding");
                }
                int high = Character.digit(raw.charAt(index + 1), 16);
                int low = Character.digit(raw.charAt(index + 2), 16);
                if (high < 0 || low < 0) {
                    throw new IOException("Malformed percent encoding");
                }
                bytes.write((high << 4) | low);
                index += 3;
            } else {
                if (ch > 0x7f) {
                    throw new IOException("Invitation code must be UTF-8 percent encoded");
                }
                bytes.write(ch);
                index++;
            }
        }
        try {
            return StandardCharsets.UTF_8.newDecoder()
                    .onMalformedInput(CodingErrorAction.REPORT)
                    .onUnmappableCharacter(CodingErrorAction.REPORT)
                    .decode(ByteBuffer.wrap(bytes.toByteArray()))
                    .toString();
        } catch (CharacterCodingException exception) {
            throw new IOException("Invitation code is not valid UTF-8", exception);
        }
    }

    public MysterType type() {
        return type;
    }

    public ServerCid bootstrap() {
        return bootstrap;
    }

    public byte[] invitationId() {
        return invitationId.clone();
    }

    /** Returns a parsed code supplied by an external producer; generated links never contain one. */
    public Optional<String> code() {
        return code;
    }

    /** Returns the password-free canonical URI safe for display and copying. */
    public URI toUri() {
        return URI.create("myster://join-type/v1?type=" + type.toHexString()
                + "&bootstrap=" + bootstrap.asHex()
                + "&invitation=" + HEX.formatHex(invitationId));
    }

    @Override
    public String toString() {
        return toUri().toASCIIString();
    }
}
